name: Nodejs-app

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use self-hosted runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build

    - name: Install PM2
      run: npm install -g pm2

    - name: Deploy and Start Application with PM2
      run: |
        if pm2 describe Nodejs-app > /dev/null; then 
          pm2 delete Nodejs-app; 
        fi
        pm2 start app.js --name "Nodejs-app"
        pm2 save
        pm2 startup

    - name: Reboot Machine
      run: sudo reboot
