name: Nodejs Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use self-hosted runner (machine)

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Node.js version jo project ke liye required hai

    - name: Install Dependencies
      run: npm install

    - name: Install PM2 Globally
      run: npm install -g pm2

    - name: Build Application
      run: npm run build

    - name: Deploy Application Using PM2
      run: |
        pm2 stop portfolio || true                      # Stop any existing instance
        pm2 delete portfolio || true                    # Remove it from PM2 list
        pm2 start app.js --name "portfolio" --watch     # Start app in PM2 with live file watching
        pm2 save                                        # Save PM2 process list for auto-restart

    - name: Set PM2 Startup Script (Persistent After Reboot)
      run: |
        pm2 unstartup || true                           # Remove any old startup configs
        pm2 startup --silent                            # Generate startup script
        pm2 save                                        # Save new PM2 process list
